### ISSUE TITLE
Unify functional metrics names

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#729]
## 🚀 Feature

let's unify the names of the metrics across the package and use `sklearn` and good [reference](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) 

### Motivation

let's apply the same assumption for all domains and preferably use fully expanded names (as a new person to the domain may not know the particular abbreviation)

### Pitch

be consistent across domains and close to standard

### Alternatives

each of these can be taken as a separate PR

- [ ] `f1` -> `f1_score`
- [ ] `fbeta` -> `fbeta_score`
- [ ] `hinge` -> `hinge_loss`
- [ ] `pit` -> `permutation_invariant_training`
- [ ] `pit_permutate` -> ???
- [ ] `psnr` -> `peak_signal_noise_ratio`
- [ ] `sdr` -> `signal_distortion_ratio` #711
- [ ] `si_sdr` -> `scale_invariant_signal_distortion_ratio` #711
- [ ] `snr` -> `signal_noise_ratio` #712
- [ ] `si_snr` -> `scale_invariant_signal_noise_ratio` #712
- [ ] `ssim` -> `structual_similarity_index_measure`
- [x] `wer` -> `word_error_rate` #714

**Comment by getgaurav2** [comment]
@Borda  - I will  take `hinge -> hinge_loss`...Thank you

**Comment by puhuk** [comment]
@Borda Can I take pit

**Comment by cuent** [comment]
I can take `fbeta_score` if @Fariborzzz hasn't yet started 😄

**Comment by Fariborzzz** [comment]
@cuent Take it please. 
I'm having some problems with my local git, might take some time to fix it 😄.

**Comment by cuent** [comment]
Okay, :) if you have working commits, I can start from there 😄

**Comment by Fariborzzz** [comment]
> 
here is the commit which also includes PSNR changes.  https://github.com/PyTorchLightning/metrics/pull/732/commits/8c7c062dbc750bbf1faa1e85eb8235ef4253f044

**Comment by Borda** [comment]
> > Okay, :) if you have working commits, I can start from there smile
> 
> here is the commit which also includes PSNR changes. [8c7c062](https://github.com/PyTorchLightning/metrics/commit/8c7c062dbc750bbf1faa1e85eb8235ef4253f044)

still would need back-compatibility patch but good start :rabbit:

**Comment by Borda** [comment]
Well done everyone!
@cuent @Fariborzzz @puhuk @getgaurav2
