### ISSUE TITLE
Remove deprecated code for next v0.9

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#956]
## 🚀 Feature

Let's start standard deprecated API cleaning and also split it into smaller contributions that are not affecting each other, and they are easier/faster to review... So each of the following ToDO shall be addressed in a single PR.
Before you start working on any, pls ping/comment us here so we can assign it to you to reduce work collision :rabbit: 

### Motivation

Regular API cleaning of deprecated API keeping the codebase in a healthy state

### Pitch

Ideal hands-on / first contribution because of its low complexity :purple_heart: 

### Alternatives

- [x] `compute_on_step` in aggregation -> #990
- [x] `compute_on_step` in audio -> #1007
- [x] `compute_on_step` in classification -> #962
- [x] `compute_on_step` in detection -> #1005
- [x] `compute_on_step` in image -> #979
- [x] `compute_on_step` in regression -> #967
- [x] `compute_on_step` in retrival -> #993
- [x]  `compute_on_step` in text -> #1004
- [x] `compute_on_step` in wrappers -> #991

**Comment by tanmoyio** [comment]
`compute_on_step` in classification 🖐

**Comment by tanmoyio** [comment]
`compute_on_step` in audio 🖐

**Comment by vumichien** [comment]
I will work on `compute_on_step` in regression

**Comment by phaseolud** [comment]
Hey, I would like to work on compute_on_step in image, is that possible?

**Comment by stancld** [comment]
> Hey, I would like to work on compute_on_step in image, is that possible?

Yes, definitely! Feel free to start! :]

**Comment by phaseolud** [comment]
I would like to pick up retrieval as well! 😄

**Comment by SkafteNicki** [comment]
@tanmoyio how is it going with the change for audio?

**Comment by tanmoyio** [comment]
@tanmoyio sorry I was in vacation, I will do it today.

**Comment by Borda** [comment]
Cool! :tada: Thank you all!
